### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by atefBB** [rashidlaasri/build-a-guestbook-with-laravel-and-vuejs#1]
the <a href="https://scotch.io/@RachidLaasri/build-a-guestbook-with-laravel-and-vuejs" target="_blank">link</a> in the project description send me to `404` error page !

**Comment by boyfromhell** [comment]
This is the [Link](https://scotch.io/tutorials/build-a-guestbook-with-laravel-and-vuejs)

**Comment by atefBB** [comment]
Thanks
